[package]
name = "glyph-gl"
version = "1.0.0"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
thiserror = "2.0.17"
clap = { version = "4.5.53", features = ["derive"] }

[profile.release]
debug = true
